### ISSUE TITLE
Update categories when adding a new category

### ISSUE THREAD

**Issue by mnofresno** [mnofresno/interact-images#12]
The sidemenu list of categories and the home page categories list doesn't update when you add a new categories in the category CRUD.

**Comment by leocreo** [comment]
Fixed. I added a new event listener to that actions. Anyway I think event logic need to be moved inside Services (Categorias/Images) and not emited from inside Controllers. I did't do that way because this will need some more code refactor.

About the good use of a Pub/Sub service to give the objects event features, I think this is the best practices and flexible way to emit an bind events and keep all code sincronized. Anyway if you think this is not the best solutions, of course feel free to remove that logic.

**Comment by mnofresno** [comment]
@leocreo I agree with you, we must refactor the logic inside the controller and put it in the services.

For the time being I will let generic event logic as it is, even though it is an excessive way to resolve a simple application like this (for the moment) however it is not a bad idea to keep it with a more versatile solution just in case.

Thanks again!
